### PR TITLE
feat(styles): add transparent windows controls

### PR DESCRIPTION
**Pull request by DianP**
## Purposes
First of all, i love your theme. 

This PR is a proposal to add transparent windows control for better visual consistency.
The code it self is not mine, i get it from spicetify discord [thread here](https://discord.com/channels/842219447716151306/1113028484349038593)

### Screenshot
image

### CODE REVIEW

**Comment by sanoojes** [comment]
Thanks for the contribution! 
Merging for transparent windows!

**Review by sanoojes — COMMENTED** [review]
thanks for the contribution !

**Comment by sanoojes** [comment]
its having issues with the linux and macos users i will make it windows specific

**Comment by DianP** [comment]
> @DianP its having issues with the linux and macos users i will make it windows specific

Sorry my bad, haven't test it on other OS, 
if you need me to make it windows only let me know.

**Comment by sanoojes** [comment]
> > @DianP its having issues with the linux and macos users i will make it windows specific
> 
> Sorry my bad, haven't test it on other OS, if you need me to make it windows only let me know.

yepp no probs i fixed it https://github.com/sanoojes/better-bloom/commit/15c3f477a4db1c5e9db1730edff1d0d5dc3ed474

**Comment by DianP** [comment]
> > > @DianP its having issues with the linux and macos users i will make it windows specific
> > 
> > 
> > Sorry my bad, haven't test it on other OS, if you need me to make it windows only let me know.
> 
> yepp no probs i fixed it [15c3f47](https://github.com/sanoojes/better-bloom/commit/15c3f477a4db1c5e9db1730edff1d0d5dc3ed474)

@sanoojes  Got it, i just finish mine here: 6bea87d
 i also add check for color-scheme light because its kinda introduce unusable styling for light theme after i test it.

if you need it i can send another PR.

**Comment by sanoojes** [comment]
oo thanks i will use this am refactoring the code a bit now

**Comment by sanoojes** [comment]
https://github.com/sanoojes/better-bloom/commit/16781f188bf2bf65235dd911939095b73a91704e

**Pull request merged**
